apiVersion: apps/v1
kind: Deployment
metadata:
  name: authzed-go
  labels:
    name: authzed-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authzed-go
  template:
    metadata:
      labels:
        app: authzed-go
    spec:
      containers:
        - name: authzed
          image: registry.cn-hangzhou.aliyuncs.com/xiaocui_server/authzed-go:main
          ##imagePullPolicy: Never
          ports:
            - containerPort: 8088
          env:
            - name: "HOST"
              value: "spicedb-svc:50051"
---
apiVersion: v1
kind: Service
metadata:
  name: authzed-go-svc
  labels:
    app: authzed-go-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30000
      port: 8080
      targetPort: 9192
      protocol: TCP
  selector:
    app: authzed-go

