apiVersion: apps/v1
kind: Deployment
metadata:
  name: authzed-go
  labels:
    name: authzed-go
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authzed-go
  template:
    metadata:
      labels:
        app: authzed-go
    spec:
      containers:
        - name: authzed
          image: authzed
          imagePullPolicy: Never # 使用本地镜像
          ports:
            - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: authzed-go
  labels:
    app: authzed-go
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 9192
  selector:
    app: authzed-go

