apiVersion: apps/v1
kind: Deployment
metadata:
  name: spicedb
  labels:
    name: spicedb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spicedb
  template:
    metadata:
      labels:
        app: spicedb
    spec:
      containers:
        - name: spicedb
          image: quay.io/authzed/spicedb:latest
          imagePullPolicy: Always
          command: ["spicedb","serve"]
          #args: ["spicedb", "migrate", "head", "--datastore-engine=postgres","--datastore-conn-uri=postgres://postgres:postgres@postgres-svc:5432/postgres?sslmode=disable" ]
#          args:
#            - spicedb
#            - migrate
#            - head
          env:
            - name: "SPICEDB_LOG_LEVEL"
              value: "debug"
            - name: "SPICEDB_HTTP_ENABLED"
              value: "true"
            - name: "SPICEDB_GRPC_SHUTDOWN_GRACE_PERIOD"
              value: "1s"
            - name: "SPICEDB_GRPC_PRESHARED_KEY"
              valueFrom:
                secretKeyRef:
                  name: "spicedb"
                  key: "SPICEDB_GRPC_PRESHARED_KEY"
            - name: "SPICEDB_DATASTORE_ENGINE"
              value: "postgres"
            - name: "SPICEDB_DATASTORE_CONN_URI"
              value: "postgres://postgres:postgres@postgres-svc:5432/postgres?sslmode=disable"
          #depends_on: migrate
          ports:
            - name: "grpc"
              containerPort: 50051
              protocol: "TCP"
            - name: "http"
              containerPort: 8443
              protocol: "TCP"
            - name: "dispatch"
              containerPort: 50053
              protocol: "TCP"
            - name: "prometheus"
              containerPort: 9090
              protocol: "TCP"
          readinessProbe:
            exec:
              command: [ "grpc_health_probe", "-v", "-addr=localhost:50051" ]
            failureThreshold: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: spicedb-svc
  labels:
    app: spicedb-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
  namespace: default
spec:
  selector:
    app: spicedb
  type: ClusterIP
  ports:
    - name: "grpc"
      port: 50051
      protocol: "TCP"
      targetPort: 50051
    - name: "http"
      port: 8443
      protocol: "TCP"
      targetPort: 8443
    - name: "dispatch"
      port: 50053
      protocol: "TCP"
      targetPort: 50053
    - name: "prometheus"
      port: 9090
      protocol: "TCP"
      targetPort: 9090

---
apiVersion: batch/v1
kind: Job
metadata:
  name: spicedb-job
spec:
  template:
    spec:
      containers:
      - name: spicedb-job
        image: quay.io/authzed/spicedb:latest
        imagePullPolicy: Always
        command: [ "spicedb","migrate","head" ]
        env:
          - name: "SPICEDB_DATASTORE_ENGINE"
            value: "postgres"
          - name: "SPICEDB_DATASTORE_CONN_URI"
            value: "postgres://postgres:postgres@postgres-svc:5432/postgres?sslmode=disable"
      restartPolicy: Never