

name: authzed-go

on:
  push:
    branches: 
      - main

jobs:
  FailJobIssueDemo:
    runs-on: ubuntu-latest
    steps:
     
      - name: install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
      - name: HTTP
        run: | 
          URL="https://cs.console.aliyun.com/hook/trigger?token=eyJhbGciOiJSUzICI6IkpXVCJ9.eyJjbHVzdGVySWQiOiJjOGU1MzFkYTgyNDZjNGVhN2E1Y2U1MGM2ODkzZmFmMGYiLCJpZCI6IjIxNDI4MSJ9.osogZm3Pv3Rzxhs9pd-OGtzZ9bIK-FJKXgeENnfZtQwuv9EZBu_d_lNE6nJmbgGvy-WXzYLIW9oK0vy_9D5c_gZ9uL2lxUTVJXfSw6XGNdt-D7l9meStn_-HG5YJK3eVSdUN2EFwuHbUHtPt-zjMtn-TW5wzXfpsFqCEETYgFj4"
          RESULT=$(curl -s ${URL})
          
          echo ${RESULT} | yq  '.codee' 
          CODE=${RESULT: 13: 3}
          if [ $CODE != "200" ]; then echo "FAILURE" ; exit 1 else echo "SUCCESS"; fi
