

name: authzed-go

on:
  push:
    branches: 
      - main

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: test get
        if: ${{ failure() }}
        run: code=curl https://cs.console.aliyun.com/hook/trigger
